/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const TradeEvent = IDL.Record({
  'action' : IDL.Text,
  'network' : IDL.Text,
  'walletAddress' : IDL.Text,
  'socialHandle' : IDL.Text,
  'tokenSymbol' : IDL.Text,
  'timestamp' : Time,
  'tokenName' : IDL.Text,
  'priceUSD' : IDL.Float64,
  'amount' : IDL.Float64,
});
export const Token = IDL.Record({
  'tokenSymbol' : IDL.Text,
  'tokenName' : IDL.Text,
});

export const idlService = IDL.Service({
  'addToWatchlist' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'getAllTradeEventsSorted' : IDL.Func([], [IDL.Vec(TradeEvent)], ['query']),
  'getWatchlist' : IDL.Func([IDL.Text], [IDL.Vec(Token)], ['query']),
  'removeFromWatchlist' : IDL.Func([IDL.Text, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const TradeEvent = IDL.Record({
    'action' : IDL.Text,
    'network' : IDL.Text,
    'walletAddress' : IDL.Text,
    'socialHandle' : IDL.Text,
    'tokenSymbol' : IDL.Text,
    'timestamp' : Time,
    'tokenName' : IDL.Text,
    'priceUSD' : IDL.Float64,
    'amount' : IDL.Float64,
  });
  const Token = IDL.Record({
    'tokenSymbol' : IDL.Text,
    'tokenName' : IDL.Text,
  });
  
  return IDL.Service({
    'addToWatchlist' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'getAllTradeEventsSorted' : IDL.Func([], [IDL.Vec(TradeEvent)], ['query']),
    'getWatchlist' : IDL.Func([IDL.Text], [IDL.Vec(Token)], ['query']),
    'removeFromWatchlist' : IDL.Func([IDL.Text, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };